services:
  - type: web
    name: nba-betting-frontend
    env: static
    buildCommand: ""
    staticPublishPath: .
    routes:
      # Make the NBA slate the homepage without breaking data asset paths
      - type: redirect
        source: /
        destination: /web/
