services:
  - type: static_site
    name: nba-betting-frontend
    env: static
    buildCommand: ""
    staticPublishPath: .
    routes:
      - type: redirect
        source: /
        destination: /web/
